src/Entity/Parts/AssociationType.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts;

/**
 * The values of this enums are used to describe how two parts are associated with each other.
 */
enum AssociationType: int
{
    /** A user definable association type, which can be described in the comment field */
    case OTHER = 0;
    /** The owning part is compatible with the other part  */
    case COMPATIBLE = 1;
    /** The owning part supersedes the other part (owner is newer version) */
    case SUPERSEDES = 2;

    /**
     * Returns the translation key for this association type.
     * @return string
     */
    public function getTranslationKey(): string
    {
        return 'part_association.type.' . strtolower($this->name);
    }
}

src/Entity/Parts/ManufacturingStatus.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts;

enum ManufacturingStatus: string
{
    /** Part has been announced, but is not in production yet */
    case ANNOUNCED = 'announced';
    /** Part is in production and will be for the foreseeable future */
    case ACTIVE = 'active';
    /** Not recommended for new designs. */
    case NRFND = 'nrfnd';
    /** End of life: Part will become discontinued soon */
    case EOL = 'eol';
    /** Part is obsolete/discontinued by the manufacturer. */
    case DISCONTINUED = 'discontinued';

    /** Status not set */
    case NOT_SET = '';

    public function toTranslationKey(): string
    {
        return match ($this) {
            self::ANNOUNCED => 'm_status.announced',
            self::ACTIVE => 'm_status.active',
            self::NRFND => 'm_status.nrfnd',
            self::EOL => 'm_status.eol',
            self::DISCONTINUED => 'm_status.discontinued',
            self::NOT_SET => '',
        };
    }
}

src/Entity/Parts/PartTraits/AdvancedPropertyTrait.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts\PartTraits;

use App\Entity\Parts\InfoProviderReference;
use Doctrine\DBAL\Types\Types;
use App\Entity\Parts\Part;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;

/**
 * Advanced properties of a part, not related to a more specific group.
 */
trait AdvancedPropertyTrait
{
    /**
     * @var bool Determines if this part entry needs review (for example, because it is work in progress)
     */
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $needs_review = false;

    /**
     * @var string A comma separated list of tags, associated with the part
     */
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $tags = '';

    /**
     * @var float|null How much a single part unit weighs in grams
     */
    #[Assert\PositiveOrZero]
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    protected ?float $mass = null;

    /**
     * @var string|null The internal part number of the part
     */
    #[Assert\Length(max: 100)]
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::STRING, length: 100, unique: true, nullable: true)]
    #[Length(max: 100)]
    protected ?string $ipn = null;

    /**
     * @var InfoProviderReference The reference to the info provider, that provided the information about this part
     */
    #[ORM\Embedded(class: InfoProviderReference::class, columnPrefix: 'provider_reference_')]
    #[Groups(['full', 'part:read'])]
    protected InfoProviderReference $providerReference;

    /**
     * Checks if this part is marked, for that it needs further review.
     */
    public function isNeedsReview(): bool
    {
        return $this->needs_review;
    }

    /**
     * Sets the "needs review" status of this part.
     *
     * @param bool $needs_review The new status
     *
     * @return Part|self
     */
    public function setNeedsReview(bool $needs_review): self
    {
        $this->needs_review = $needs_review;

        return $this;
    }

    /**
     * Gets a comma separated list, of tags, that are assigned to this part.
     */
    public function getTags(): string
    {
        return $this->tags;
    }

    /**
     * Sets a comma separated list of tags, that are assigned to this part.
     *
     * @param string $tags The new tags
     *
     * @return $this
     */
    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Returns the mass of a single part unit.
     * Returns null, if the mass is unknown/not set yet.
     */
    public function getMass(): ?float
    {
        return $this->mass;
    }

    /**
     * Sets the mass of a single part unit.
     * Sett to null, if the mass is unknown.
     *
     * @param float|null $mass the new mass
     *
     * @return $this
     */
    public function setMass(?float $mass): self
    {
        $this->mass = $mass;

        return $this;
    }

    /**
     * Returns the internal part number of the part.
     * @return string
     */
    public function getIpn(): ?string
    {
        return $this->ipn;
    }

    /**
     * Sets the internal part number of the part
     * @param  string  $ipn The new IPN of the part
     */
    public function setIpn(?string $ipn): Part
    {
        $this->ipn = $ipn;
        return $this;
    }

    /**
     * Returns the reference to the info provider, that provided the information about this part.
     * @return InfoProviderReference
     */
    public function getProviderReference(): InfoProviderReference
    {
        return $this->providerReference;
    }

    /**
     * Sets the reference to the info provider, that provided the information about this part.
     * @param  InfoProviderReference  $providerReference
     * @return Part
     */
    public function setProviderReference(InfoProviderReference $providerReference): Part
    {
        $this->providerReference = $providerReference;
        return $this;
    }




}

src/Entity/Parts/PartTraits/EDATrait.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts\PartTraits;

use App\Entity\EDA\EDAPartInfo;
use Doctrine\ORM\Mapping\Embedded;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints\Valid;

trait EDATrait
{
    #[Valid]
    #[Embedded(class: EDAPartInfo::class)]
    #[Groups(['full', 'part:read', 'part:write'])]
    protected EDAPartInfo $eda_info;

    public function getEdaInfo(): EDAPartInfo
    {
        return $this->eda_info;
    }

    public function setEdaInfo(?EDAPartInfo $eda_info): self
    {
        if ($eda_info !== null) {
            //Do a clone, to ensure that the property is updated in the database
            $eda_info = clone $eda_info;
        }

        $this->eda_info = $eda_info;
        return $this;
    }
}

src/Entity/Parts/PartTraits/InstockTrait.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts\PartTraits;

use Doctrine\DBAL\Types\Types;
use App\Entity\Parts\MeasurementUnit;
use App\Entity\Parts\PartLot;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Attribute\SerializedName;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This trait collects all aspects of a part related to instock, part lots.
 */
trait InstockTrait
{
    /**
     * @var Collection<int, PartLot> A list of part lots where this part is stored
     */
    #[Assert\Valid]
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\OneToMany(mappedBy: 'part', targetEntity: PartLot::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['amount' => 'DESC'])]
    protected Collection $partLots;

    /**
     * @var float The minimum amount of the part that has to be instock, otherwise more is ordered.
     *            Given in the partUnit.
     */
    #[Assert\PositiveOrZero]
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::FLOAT)]
    protected float $minamount = 0;

    /**
     * @var ?MeasurementUnit the unit in which the part's amount is measured
     */
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\ManyToOne(targetEntity: MeasurementUnit::class)]
    #[ORM\JoinColumn(name: 'id_part_unit')]
    protected ?MeasurementUnit $partUnit = null;

    /**
     * Get all part lots where this part is stored.
     * @phpstan-return Collection<int, PartLot>
     */
    public function getPartLots(): Collection
    {
        return $this->partLots;
    }

    /**
     * Adds the given part lot, to the list of part lots.
     * The part lot is assigned to this part.
     *
     * @return $this
     */
    public function addPartLot(PartLot $lot): self
    {
        $lot->setPart($this);
        $this->partLots->add($lot);

        return $this;
    }

    /**
     * Removes the given part lot from the list of part lots.
     *
     * @param PartLot $lot the part lot that should be deleted
     *
     * @return $this
     */
    public function removePartLot(PartLot $lot): self
    {
        $this->partLots->removeElement($lot);

        return $this;
    }

    /**
     * Gets the measurement unit in which the part's amount should be measured.
     * Returns null if no specific unit was that. That means the parts are measured simply in quantity numbers.
     */
    public function getPartUnit(): ?MeasurementUnit
    {
        return $this->partUnit;
    }

    /**
     * Sets the measurement unit in which the part's amount should be measured.
     * Set to null, if the part should be measured in quantities.
     *
     * @return $this
     */
    public function setPartUnit(?MeasurementUnit $partUnit): self
    {
        $this->partUnit = $partUnit;

        return $this;
    }

    /**
     *  Get the count of parts which must be in stock at least.
     * If an integer-based part unit is selected, the value will be rounded to integers.
     *
     * @return float count of parts which must be in stock at least
     */
    public function getMinAmount(): float
    {
        if ($this->useFloatAmount()) {
            return $this->minamount;
        }

        return round($this->minamount);
    }

    /**
     * Checks if this part uses the float amount .
     * This setting is based on the part unit (see MeasurementUnit->isInteger()).
     *
     * @return bool True if the float amount field should be used. False if the integer instock field should be used.
     */
    public function useFloatAmount(): bool
    {
        if ($this->partUnit instanceof MeasurementUnit) {
            return !$this->partUnit->isInteger();
        }

        //When no part unit is set, treat it as part count, and so use the integer value.
        return false;
    }

    /**
     * Returns true, if the total instock amount of this part is less than the minimum amount.
     */
    public function isNotEnoughInstock(): bool
    {
        return $this->getAmountSum() < $this->getMinAmount();
    }

    /**
     * Returns true, if at least one of the part lots has an unknown amount.
     * It is possible that other part lots have a known amount, then getAmountSum() will return sum of all known amounts.
     * @return bool True if at least one part lot has an unknown amount.
     */
    public function isAmountUnknown(): bool
    {
        foreach ($this->getPartLots() as $lot) {
            if ($lot->isInstockUnknown()) {
                return true;
            }
        }

        return false;
    }

    /**
     * Returns the summed amount of this part (over all part lots)
     * Part Lots that have unknown value or are expired, are not used for this value (counted as 0).
     *
     * @return float The amount of parts given in partUnit
     */
    #[Groups(['simple', 'extended', 'full', 'part:read'])]
    #[SerializedName('total_instock')]
    public function getAmountSum(): float
    {
        //TODO: Find a method to do this natively in SQL, the current method could be a bit slow
        $sum = 0;
        foreach ($this->getPartLots() as $lot) {
            //Don't use the in stock value, if it is unknown
            if ($lot->isInstockUnknown() || ($lot->isExpired() ?? false)) {
                continue;
            }

            $sum += $lot->getAmount();
        }

        if ($this->useFloatAmount()) {
            return $sum;
        }

        return round($sum);
    }

    /**
     * Returns the summed amount of all part lots that are expired. If no part lots are expired 0 is returned.
     */
    public function getExpiredAmountSum(): float
    {
        $sum = 0.0;
        foreach ($this->getPartLots() as $lot) {
            if ($lot->isExpired() && !$lot->isInstockUnknown()) {
                $sum += $lot->getAmount();
            }
        }

        if ($this->useFloatAmount()) {
            return $sum;
        }

        return round($sum);
    }

    /**
     * Set the minimum amount of parts that have to be instock.
     * See getPartUnit() for the associated unit.
     *
     * @param float $new_minamount the new count of parts which should be in stock at least
     *
     * @return $this
     */
    public function setMinAmount(float $new_minamount): self
    {
        $this->minamount = $new_minamount;

        return $this;
    }
}

templates/parts/lists/_action_bar.html.twig
<div class="row mb-3">
    <div class="col">
        <a href="{{ path('part_new', url_options) }}" class="btn btn-success float-start {% if not is_granted("@parts.create") or (entity is defined and entity.notSelectable) %}disabled{% endif %}"><i class="fas fa-plus-square fa-fw"></i>
            {% trans%}part.create.btn{% endtrans %}</a>
    </div>
</div>

templates/parts/lists/_filter.html.twig
<div class="accordion-item">
    <div class="accordion-header">
        <button class="accordion-button collapsed py-2" type="button" data-bs-toggle="collapse" data-bs-target="#filterFormCollapse" aria-expanded="false" aria-controls="filterFormCollapse"><i class="fa-solid fa-filter fa-fw"></i> {% trans %}filter.title{% endtrans %}</button>
    </div>
    <div id="filterFormCollapse" class="accordion-collapse collapse" data-bs-parent="#listAccordion">
        <div class="accordion-body">
            <ul class="nav nav-tabs" id="filterTabs" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="filter-common-tab" data-bs-toggle="tab" data-bs-target="#filter-common"><i class="fas fa-id-card fa-fw"></i> {% trans %}part.edit.tab.common{% endtrans %}</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="filter-manufacturer-tab" data-bs-toggle="tab" data-bs-target="#filter-manufacturer"><i class="fas fa-industry fa-fw"></i> {% trans %}part.edit.tab.manufacturer{% endtrans %}</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="filter-advanced-tab" data-bs-toggle="tab" data-bs-target="#filter-advanced"><i class="fas fa-shapes fa-fw"></i> {% trans %}part.edit.tab.advanced{% endtrans %}</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="filter-stocks-tab" data-bs-toggle="tab" data-bs-target="#filter-stocks"><i class="fas fa-boxes fa-fw"></i> {% trans %}part.edit.tab.part_lots{% endtrans %}</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="filter-attachments-tab" data-bs-toggle="tab" data-bs-target="#filter-attachments"><i class="fas fa-paperclip fa-fw"></i> {% trans %}part.edit.tab.attachments{% endtrans %}</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="filter-orderdetails-tab" data-bs-toggle="tab" data-bs-target="#filter-orderdetails"><i class="fas fa-shopping-cart fa-fw"></i> {% trans %}part.edit.tab.orderdetails{% endtrans %}</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="filter-parameters-tab" data-bs-toggle="tab" data-bs-target="#filter-parameters"><i class="fas fa-atlas fa-fw"></i> {% trans %}part.edit.tab.specifications{% endtrans %}</button>
                </li>
                {% if filterForm.project is defined %}
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="filter-projects-tab" data-bs-toggle="tab" data-bs-target="#filter-projects"><i class="fas fa-archive fa-fw"></i> {% trans %}project.labelp{% endtrans %}</button>
                    </li>
                {% endif %}
            </ul>

            {{ form_start(filterForm, {"attr": {"data-controller": "helpers--form-cleanup", "data-action": "helpers--form-cleanup#submit"}}) }}

            <div class="tab-content">
                <div class="tab-pane active pt-3" id="filter-common" role="tabpanel" aria-labelledby="filter-common-tab" tabindex="0">
                    {{ form_row(filterForm.name) }}
                    {{ form_row(filterForm.description) }}
                    {{ form_row(filterForm.category) }}
                    {{ form_row(filterForm.footprint) }}
                    {{ form_row(filterForm.tags) }}
                    {{ form_row(filterForm.comment) }}
                </div>

                <div class="tab-pane pt-3" id="filter-manufacturer" role="tabpanel" aria-labelledby="filter-manufacturer-tab" tabindex="0">
                    {{ form_row(filterForm.manufacturer) }}
                    {{ form_row(filterForm.manufacturing_status) }}
                    {{ form_row(filterForm.manufacturer_product_number) }}
                    {{ form_row(filterForm.manufacturer_product_url) }}
                </div>

                <div class="tab-pane pt-3" id="filter-advanced" role="tabpanel" aria-labelledby="filter-advanced-tab" tabindex="0">
                    {{ form_row(filterForm.favorite) }}
                    {{ form_row(filterForm.needsReview) }}
                    {{ form_row(filterForm.measurementUnit) }}
                    {{ form_row(filterForm.mass) }}
                    {{ form_row(filterForm.dbId) }}
                    {{ form_row(filterForm.ipn) }}
                    {{ form_row(filterForm.lastModified) }}
                    {{ form_row(filterForm.addedDate) }}
                </div>

                <div class="tab-pane pt-3" id="filter-stocks" role="tabpanel" aria-labelledby="filter-stocks-tab" tabindex="0">
                    {{ form_row(filterForm.storelocation) }}
                    {{ form_row(filterForm.minAmount) }}
                    {{ form_row(filterForm.amountSum) }}
                    {{ form_row(filterForm.lessThanDesired) }}
                    {{ form_row(filterForm.lotCount) }}
                    {{ form_row(filterForm.lotExpirationDate) }}
                    {{ form_row(filterForm.lotDescription) }}
                    {{ form_row(filterForm.lotOwner) }}
                    {{ form_row(filterForm.lotNeedsRefill) }}
                    {{ form_row(filterForm.lotUnknownAmount) }}
                </div>

                <div class="tab-pane pt-3" id="filter-attachments" role="tabpanel" aria-labelledby="filter-attachments-tab" tabindex="0">
                    {{ form_row(filterForm.attachmentsCount) }}
                    {{ form_row(filterForm.attachmentType) }}
                    {{ form_row(filterForm.attachmentName) }}
                </div>

                <div class="tab-pane pt-3" id="filter-orderdetails" role="tabpanel" aria-labelledby="filter-orderdetails-tab" tabindex="0">
                    {{ form_row(filterForm.supplier) }}
                    {{ form_row(filterForm.orderdetailsCount) }}
                    {{ form_row(filterForm.obsolete) }}
                </div>

                <div class="tab-pane pt-3" id="filter-parameters" role="tabpanel" aria-labelledby="filter-parameters-tab" tabindex="0">
                    {% import 'components/collection_type.macro.html.twig' as collection %}
                    {{ form_row(filterForm.parametersCount) }}

                    <div {{ collection.controller(filterForm.parameters) }}>
                        <table class="table table-striped table-sm" id="lots_table" {{ collection.target() }}>
                            <thead>
                            <tr>
                                <th>{% trans %}specifications.property{% endtrans %}</th>
                                <th>{% trans %}specifications.symbol{% endtrans %}</th>
                                <th>{% trans %}specifications.value{% endtrans %}</th>
                                <th>{% trans %}specifications.unit{% endtrans %}</th>
                                <th>{% trans %}specifications.text{% endtrans %}</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for param in filterForm.parameters %}
                                {{ form_widget(param) }}
                            {% endfor %}
                            </tbody>
                        </table>

                        <button type="button" class="btn btn-success" {{ collection.create_btn() }}>
                            <i class="fas fa-plus-square fa-fw"></i>
                            {% trans %}filter.constraint.add{% endtrans %}
                        </button>
                    </div>
                </div>

                {% if filterForm.project is defined %}
                    <div class="tab-pane pt-3" id="filter-projects" role="tabpanel" aria-labelledby="filter-projects-tab" tabindex="0">
                        {{ form_row(filterForm.project) }}
                        {{ form_row(filterForm.bomQuantity) }}
                        {{ form_row(filterForm.bomName) }}
                        {{ form_row(filterForm.bomComment) }}
                    </div>
                {% endif %}

            </div>


            {{ form_row(filterForm.submit) }}
            {{ form_row(filterForm.discard) }}

            <div class="row mb-3">
                <div class="col-sm-9 offset-sm-3">
                    <button type="button" class="btn btn-danger" {{ stimulus_action('helpers/form_cleanup', 'clearAll') }}>{% trans %}filter.clear_filters{% endtrans %}</button>
                </div>
            </div>

            {# Retain the query parameters of the search form if it is existing #}
            {% if searchFilter is defined %}
                {% for property, value in searchFilter|to_array %}
                    <input type="hidden" name="{{ property }}" data-no-clear="true" value="{{ value }}">
                {% endfor %}

            {% endif %}

            {{ form_end(filterForm) }}
        </div>
    </div>
</div>

templates/parts/lists/_parts_list.html.twig
{% import "components/datatables.macro.html.twig" as datatables %}

{{ datatables.partsDatatableWithForm(datatable) }}

templates/parts/lists/all_list.html.twig
{% extends "base.html.twig" %}

{% block  title %}
    {% trans %}parts_list.all.title{% endtrans %}
{% endblock %}

{% block content %}

    <div class="accordion mb-3" id="listAccordion">
        <div class="accordion-item">
            <div class="accordion-header">
                <button class="accordion-button collapsed py-2" data-bs-toggle="collapse" data-bs-target="#searchInfo" disabled>
                    <i class="fa-solid fa-globe fa-fw"></i>
                    {% trans %}parts_list.all.title{% endtrans %}
                </button>
            </div>
            <div id="searchInfo" class="accordion-collapse collapse" data-bs-parent="#listAccordion">
                <div class="accordion-body">

                </div>
            </div>
        </div>

        {% include "parts/lists/_filter.html.twig" %}
    </div>

    {% include "parts/lists/_action_bar.html.twig" with {'url_options': {}} %}
    {% include "parts/lists/_parts_list.html.twig" %}

{% endblock %}

templates/parts/lists/category_list.html.twig
{% extends "base.html.twig" %}

{% block  title %}
    {% trans %}parts_list.category.title{% endtrans %} {{ entity.name }}
{% endblock %}

{% block content %}

    {% include "parts/lists/_info_card.html.twig" with {'header_label': 'category.label'} %}

    {% include "parts/lists/_action_bar.html.twig" with {'url_options': {'category': entity.iD}} %}

    {% include "parts/lists/_parts_list.html.twig" %}

{% endblock %}

templates/parts/lists/footprint_list.html.twig
{% extends "base.html.twig" %}

{% block  title %}
    {% trans %}parts_list.footprint.title{% endtrans %} {{ entity.name }}
{% endblock %}

{% block content %}

    {% include "parts/lists/_info_card.html.twig" with {'header_label': 'footprint.label'} %}

    {% include "parts/lists/_action_bar.html.twig" with {'url_options': {'footprint': entity.iD}} %}

    {% include "parts/lists/_parts_list.html.twig" %}

{% endblock %}